import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, join, relative } from "node:path";

const root = resolve(import.meta.dir, "..");
const source = join(root, "site");
const partialRoot = join(source, "partials");
function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) =>
      entry.isDirectory()
        ? walk(join(dir, entry.name))
        : [join(dir, entry.name)],
    )
    .sort();
}

// Derived from the real compositions, so the handover index cannot drift from them.
export function componentInventory() {
  const partials = new Map(
    walk(partialRoot)
      .filter((p) => p.endsWith(".hbs"))
      .map((p) => [
        relative(partialRoot, p).replace(/\.hbs$/, ""),
        readFileSync(p, "utf8"),
      ]),
  );
  const pages = readdirSync(join(source, "pages"))
    .filter((p) => p.endsWith(".json"))
    .sort()
    .map((file) => ({
      ...JSON.parse(readFileSync(join(source, "pages", file), "utf8")),
      href: file.replace(".json", ".html"),
      source: `site/pages/${file}`,
    }));
  const usage = new Map<string, Set<string>>();
  const fields = new Map<string, Set<string>>();
  const references = (text: string) =>
    [...text.matchAll(/{{>\s+([\w/-]+)/g)].map((match) => match[1]);
  for (const page of pages) {
    const seen = new Set<string>();
    function visit(name: string) {
      if (seen.has(name)) return;
      seen.add(name);
      const users = usage.get(name) || new Set<string>();
      users.add(page.href);
      usage.set(name, users);
      references(partials.get(name) || "").forEach(visit);
    }
    references(
      readFileSync(join(source, "layouts", `${page.layout}.hbs`), "utf8"),
    ).forEach(visit);
    for (const block of page.sections) {
      visit(block.component);
      const keys = fields.get(block.component) || new Set<string>();
      Object.keys(block.data || {}).forEach((key) => keys.add(key));
      fields.set(block.component, keys);
    }
  }
  const labels: Record<string, string> = {
    headers: "Headers",
    sections: "Reusable sections",
    pages: "Page-specific sections",
    shared: "Global elements",
  };
  const groups = Object.entries(labels).map(([prefix, title]) => ({
    title,
    components: [...partials.keys()]
      .filter((name) => name.startsWith(`${prefix}/`))
      .map((name) => ({
        name,
        previewHref: `component--${name.replaceAll("/", "--")}.html`,
        source: `site/partials/${name}.hbs`,
        fields: [...(fields.get(name) || [])].sort(),
        usedBy: pages
          .filter((page) => usage.get(name)?.has(page.href))
          .map((page) => ({
            href: page.href,
            title: page.title.replace(/\s+[·—].*$/, ""),
          })),
      })),
  }));
  return { total: partials.size, pageCount: pages.length, groups };
}

export function writeInventory() {
  const inventory = componentInventory();
  let markdown =
    "# Component inventory\n\nGenerated by `bun run inventory` from the current partials and page configurations. Do not edit this table by hand.\n\n";
  markdown += `${inventory.total} partials across ${inventory.pageCount} site and review page compositions. Nested shared partials are included. See [the developer handover](developer-handover.md) for CMS field mapping and [motion guidelines](motion-guidelines.md) for interaction behaviour.\n\n`;
  for (const group of inventory.groups) {
    markdown += `## ${group.title}\n\n| Component | Data keys in use | Used on |\n| --- | --- | --- |\n`;
    for (const item of group.components)
      markdown += `| [${item.name}](../${item.source}) | ${
        item.fields.length
          ? item.fields
              .map((f) => "\\`" + f + "\\`")
              .join(", ")
              .replaceAll("\\`", "`")
          : "Content in template / inherited context"
      } | ${item.usedBy.map((p) => `[${p.title}](../mockups/${p.href})`).join(", ") || "Not currently used"} |\n`;
    markdown += "\n";
  }
  mkdirSync(join(root, "docs"), { recursive: true });
  writeFileSync(join(root, "docs/component-inventory.md"), markdown);
  console.log(
    `Indexed ${inventory.total} partials and ${inventory.pageCount} page compositions.`,
  );
}
if (import.meta.main) writeInventory();
